trigger:
- none

variables:
  imageName: 'dotnetapi'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        Dockerfile: dotnetapi/Dockerfile
        containerRegistry: acrammar-registry